CREATE TABLE GUEST(
	ID VARCHAR2(20),
	PW VARCHAR2(20),
	NAME VARCHAR2(20),
	PHONE_NUMBER VARCHAR2(11),
	EMAIL VARCHAR2(20),
	POINT NUMBER(8),
	CONSTRAINT GUEST_PK PRIMARY KEY(ID)
);

--INSERT INTO GUEST
--(ID, PW, NAME, PHONE_NUMBER, EMAIL, POINT)
--VALUES('ABC123', '1234', '김범수', '01012341234', 'QJATN4793@NAVER.COM', 10000);

SELECT * FROM FIRST_C WHERE PLANE_NUM = 'P730';
SELECT COUNT(*) FROM PLANE WHERE DEPARTURE_DATE = '2020-7-19' AND DEPARTURE = 'Japan' AND ARRIVAL = 'America';
SELECT HOTEL_NUM, ROOM_COUNT FROM HOTEL_INFORMATION WHERE HOTEL_RESERVATION = 'MLSZEB';
--DROP TABLE GUEST;

CREATE TABLE PLANE_INFORMATION(
	PLANE_RESERVATION VARCHAR2(20),
	ID VARCHAR2(20),
	PLANE_NUM_1 VARCHAR2(20),
	PLANE_NUM_2 VARCHAR2(20),
	GRADE VARCHAR2(20),
	SEAT_COUNT VARCHAR2(20),
	PLANE_TOTAL_PRICE NUMBER(8),
	CONSTRAINT PLANE_INFORMATION_PK PRIMARY KEY(PLANE_RESERVATION),
	CONSTRAINT PLANE_INFORMATION_FK FOREIGN KEY(ID)REFERENCES GUEST
);

--DROP TABLE PLANE_INFORMATION;

CREATE TABLE PLANE(
	PLANE_NUM VARCHAR2(20),
	COMPANY VARCHAR2(20),
	DEPARTURE VARCHAR2(20),
	ARRIVAL VARCHAR2(20),
	DEPARTURE_DATE VARCHAR(20),
	DEPARTURE_TIME NUMBER(10),
	SEAT_TOTAL VARCHAR(20),
	CONSTRAINT PLANE_PK PRIMARY KEY(PLANE_NUM)
);

--ALTER TABLE PLANE
--RENAME COLUMN PARTURE_DATE TO DEPARTURE_DATE;
--컬럼명 변경 명령어

ALTER TABLE PLANE_INFORMATION
ADD CONSTRAINT PLANE_NUM_1_FK FOREIGN KEY(PLANE_NUM_1)
REFERENCES PLANE(PLANE_NUM);
--FK연결 명령어 PLANE_NUM_1을 FK로 지정후 연결해줘서 가능

--ALTER TABLE PLANE
--ADD CONSTRAINT PLANE_NUM_FK FOREIGN KEY(PLANE_NUM)
--REFERENCES PLANE_INFORMATION(PLANE_NUM_1);
--안됨..PLANE_NUM_1이 FK가 아니어서 연결불가

ALTER TABLE PLANE_INFORMATION
ADD CONSTRAINT PLANE_NUM_2_FK FOREIGN KEY(PLANE_NUM_2)
REFERENCES PLANE(PLANE_NUM);
--FK연결 명령어 PLANE_NUM_2를 FK로 지정후 연결해줘서 가능

--DROP TABLE PLANE_INFORMATION;

--DROP TABLE PLANE_INFORMATION;

--DROP TABLE PLANE;

CREATE TABLE FIRST_C(
	PLANE_NUM VARCHAR2(20),
	ADULT NUMBER(8),
	CHILD NUMBER(8),
	BABY NUMBER(8),
	CONSTRAINT FIRST_C_FK FOREIGN KEY(PLANE_NUM)
	REFERENCES PLANE
);

--DROP TABLE FIRST_C;

CREATE TABLE BUSINESS_C(
	PLANE_NUM VARCHAR2(20),
	ADULT NUMBER(8),
	CHILD NUMBER(8),
	BABY NUMBER(8),
	CONSTRAINT BUSINESS_C_FK FOREIGN KEY(PLANE_NUM)
	REFERENCES PLANE
);

--DROP TABLE BUSINESS_C;

CREATE TABLE ECONOMY_C(
	PLANE_NUM VARCHAR2(20),
	ADULT NUMBER(8),
	CHILD NUMBER(8),
	BABY NUMBER(8),
	CONSTRAINT ECONOMY_C_FK FOREIGN KEY(PLANE_NUM)
	REFERENCES PLANE
);

--DROP TABLE ECONOMY_C;

CREATE TABLE HOTEL_INFORMATION(
	ID VARCHAR2(20),
	HOTEL_RESERVATION VARCHAR2(20),
	HOTEL_NUM VARCHAR2(20),
	CHECK_IN VARCHAR2(20),
	CHECK_OUT VARCHAR2(20),
	ROOM_COUNT VARCHAR2(20),
	HOTEL_TOTAL_PRICE NUMBER(10),
	CONSTRAINT HOTEL_INFORMATION_PK PRIMARY KEY(HOTEL_RESERVATION),
	CONSTRAINT HOTEL_INFORMATION_FK FOREIGN KEY(ID)
	REFERENCES GUEST
);

--DROP TABLE HOTEL_INFORMATION;

CREATE TABLE HOTEL(
	HOTEL_NUM VARCHAR2(20), 
	HOTEL_NAME VARCHAR2(20),
	HOTEL_LOCATION VARCHAR2(20),
	ROOM_TOTAL VARCHAR2(20),
	CONSTRAINT HOTEL_PK PRIMARY KEY(HOTEL_NUM)
);

ALTER TABLE HOTEL_INFORMATION
ADD CONSTRAINT HOTEL_NUM_FK FOREIGN KEY(HOTEL_NUM)
REFERENCES HOTEL(HOTEL_NUM);

--DROP TABLE HOTEL;

CREATE TABLE HOTEL_CLASS(
	HOTEL_NUM VARCHAR2(20),
	ROOM_1 NUMBER(8),
	ROOM_2 NUMBER(8),
	ROOM_4 NUMBER(8),
	CONSTRAINT HOTEL_CLASS_PK PRIMARY KEY(HOTEL_NUM),
	CONSTRAINT HOTEL_CLASS_FK FOREIGN KEY(HOTEL_NUM)
	REFERENCES HOTEL
);

--DROP TABLE HOTEL_CLASS;

--INSERT INTO GUEST
--(ID, PW, NAME, PHONE_NUMBER, EMAIL, POINT)
--VALUES('ABC123', '1234', '김범수', '01012341234', 'QJATN4793@NAVER.COM', 10000);

--INSERT INTO PLANE
--(PLANE_NUM, COMPANY, DEPARTURE, ARRIVAL, DEPARTURE_DATE, DEPARTURE_TIME, SEAT_TOTAL)
-- VALUES('A01', 'Korean_air', 'Korea', 'China', '2020-5-29', 1, '3,3,10')
 
--AND BUSINESS_C AND ECONOMY_C AND FIRST_C
--(PLANE_NUM, ADULT, CHILD, BABY),
--(PLANE_NUM, ADULT, CHILD, BABY),
--(PLANE_NUM, ADULT, CHILD, BABY)
--
-- ('A01', 10000, 1000, 500),
-- ('A01', 20000, 2000, 1000),
-- ('A01', 30000, 3000, 2000);

--SELECT * FROM PLANE WHERE PLANE_NUM = 'A01';


 
--INSERT INTO ECONOMY_C
--(PLANE_NUM, ADULT, CHILD, BABY)
-- VALUES('E368', 11, 6, 4);
--
--INSERT INTO BUSINESS_C
--(PLANE_NUM, ADULT, CHILD, BABY)
-- VALUES('E368', 10, 5, 3);
--
--
--INSERT INTO FIRST_C
--(PLANE_NUM, ADULT, CHILD, BABY)
-- VALUES('E368', 9, 1, 2);
 
-- INSERT INTO PLANE
--(PLANE_NUM, COMPANY, DEPARTURE, ARRIVAL, DEPARTURE_DATE, DEPARTURE_TIME, SEAT_TOTAL)
-- VALUES(?, ?, ?, ?, ?, ?, ?)